//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationEvents
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDonation
    {
        public int Id { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string PayPalResponse { get; set; }
        public string TransactionID { get; set; }
        public string status { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
