//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationRange
    {
        public int Id { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<decimal> DonationAmount { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
